package com.example.sampleminorproject;

public class QuestionAnswerAptitude {
    public static String question[] = {
            "A train running at the speed of 60 km/h crosses a pole in 9 seconds. What is the length of the train?",
            "If a person walks at 12 km/h instead of 10 km/h, they save 10 minutes. What is the distance traveled?",
            "The average of first five multiples of 3 is:",
            "If a sum of money doubles itself in 8 years under simple interest, what is the rate of interest?",
            "Which data structure follows the LIFO principle?",
            "What is the time complexity of binary search?",
            "What will be the output of `System.out.println(5 + 5 + \"5\")` in Java?",
            "How do you declare an array in Python?",
            "What is the output of the following code snippet in Python: `print([1, 2, 3][1])`?",
            "How many primitive data types are there in Java?",
            "A man can row 9 km/h in still water. If the river is flowing at 3 km/h, it takes him 4 hours to row to a place and back. How far is the place?",
            "If 6 men or 8 women can do a work in 10 days, how long will it take 3 men and 4 women to complete the same work?",
            "What will be the output of `System.out.println(\"Hello\" + null);` in Java?",
            "A car covers a distance of 120 km at a speed of 40 km/h and returns at a speed of 60 km/h. What is the average speed for the whole journey?",
            "Which sorting algorithm is the most efficient for a nearly sorted array?",
            "In Java, which keyword is used to inherit a class?",
            "If the selling price of an article is Rs. 1500 and the loss is 25%, what is the cost price?",
            "In SQL, which command is used to remove rows from a table?",
            "What is the final percentage change if a number is increased by 20%, then decreased by 20%?",
            "What is the time complexity of accessing an element in an ArrayList?",
            "A and B together can complete a task in 8 days. B alone can complete the task in 12 days. How many days will A alone take to complete the task?",
            "What will `len({1, 2, 3, 3, 4, 5})` return in Python?",
            "If the price of sugar increases by 25%, by how much should a housewife reduce her consumption so that her expenditure remains the same?",
            "What does SQL stand for?",
            "What is the least number which when divided by 6, 7, 8, 9, and 12 leaves the same remainder 1 in each case?"
    };

    public static String[][] choices = {
            {"120 meters", "150 meters", "180 meters", "200 meters"},
            {"6 km", "12 km", "10 km", "15 km"},
            {"9", "10", "12", "15"},
            {"10%", "12.5%", "15%", "20%"},
            {"Queue", "Stack", "Array", "Linked List"},
            {"O(log n)", "O(n)", "O(n^2)", "O(1)"},
            {"55", "10", "105", "555"},
            {"array()", "array[]", "[ ]", "None of the above"},
            {"2", "3", "1", "0"},
            {"8", "6", "4", "7"},
            {"12 km", "6 km", "9 km", "4.5 km"},
            {"8 days", "9 days", "10 days", "12 days"},
            {"Error", "Hellonull", "Hello null", "Compile time error"},
            {"48 km/h", "50 km/h", "52 km/h", "55 km/h"},
            {"Quick Sort", "Bubble Sort", "Selection Sort", "Insertion Sort"},
            {"extends", "inherits", "super", "this"},
            {"Rs. 1000", "Rs. 1125", "Rs. 1200", "Rs. 1250"},
            {"DELETE", "REMOVE", "ERASE", "DROP"},
            {"4% decrease", "4% increase", "No change", "5% decrease"},
            {"O(log n)", "O(1)", "O(n)", "O(n log n)"},
            {"16 days", "20 days", "24 days", "32 days"},
            {"6", "4", "5", "7"},
            {"16%", "20%", "25%", "30%"},
            {"Structured Query Language", "Simple Query Language", "Structured Quick Language", "Sequential Query Language"},
            {"251", "301", "361", "401"}
    };

    public static String correctAnswers[] = {
            "150 meters",
            "10 km",
            "9",
            "12.5%",
            "Stack",
            "O(log n)",
            "105",
            "[ ]",
            "2",
            "8",
            "6 km",
            "10 days",
            "Error",
            "48 km/h",
            "Insertion Sort",
            "extends",
            "Rs. 2000",
            "DELETE",
            "4% decrease",
            "O(1)",
            "24 days",
            "6",
            "20%",
            "Structured Query Language",
            "361"
    };
}
