package com.example.sampleminorproject;

public class QuestionAnswerAptitude {
    public static String question[] = {
            "A train running at the speed of 60 km/h crosses a pole in 9 seconds. What is the length of the train?",
            "If a person walks at 12 km/h instead of 10 km/h, they save 10 minutes. What is the distance traveled?",
            "The average of first five multiples of 3 is:",
            "If a sum of money doubles itself in 8 years under simple interest, what is the rate of interest?",
            "A is twice as good as workman as B, and together they complete a work in 18 days. In how many days will A alone finish the work?",
            "Two pipes can fill a tank in 20 minutes and 30 minutes, respectively. How long will it take both to fill the tank together?",
            "What is the probability of getting a sum of 9 from two throws of a dice?",
            "The average age of 30 students is 15 years. When a new student is included, the average age reduces by 0.5 years. What is the age of the new student?",
            "If the selling price of an article is Rs. 1500 and the loss is 25%, what is the cost price?",
            "In how many ways can the letters of the word 'LEADER' be arranged?",
            "A man can row 9 km/h in still water. If the river is flowing at 3 km/h, it takes him 4 hours to row to a place and back. How far is the place?",
            "If 6 men or 8 women can do a work in 10 days, how long will it take 3 men and 4 women to complete the same work?",
            "In what time will Rs. 8000 amount to Rs. 9261 at 10% per annum compounded annually?",
            "A car covers a distance of 120 km at a speed of 40 km/h and returns at a speed of 60 km/h. What is the average speed for the whole journey?",
            "If a shopkeeper gives a discount of 20% on a marked price and still gains 25%, what is the cost price?",
            "If 20% of a = b, then b% of 20 is the same as:",
            "A man bought a cycle for Rs. 700 and sold it for Rs. 800. What is the gain percentage?",
            "If 12 men can do a piece of work in 20 days, how long will it take 15 men to do the same work?",
            "If a number is increased by 20%, then decreased by 20%, what is the final percentage change?",
            "If the ratio of the ages of A and B is 3:5 and the sum of their ages is 40 years, what is the age of A?",
            "A and B together can complete a task in 8 days. B alone can complete the task in 12 days. How many days will A alone take to complete the task?",
            "A man walking at 5 km/h crosses a square field diagonally in 12 minutes. What is the area of the field?",
            "If the price of sugar increases by 25%, by how much should a housewife reduce her consumption so that her expenditure remains the same?",
            "A sum of money amounts to Rs. 9800 in 2 years and Rs. 12005 in 3 years at compound interest. What is the rate of interest?",
            "What is the least number which when divided by 6, 7, 8, 9, and 12 leaves the same remainder 1 in each case?"
    };

    public static String[][] choices = {
            {"120 meters", "150 meters", "180 meters", "200 meters"},
            {"6 km", "12 km", "10 km", "15 km"},
            {"9", "10", "12", "15"},
            {"10%", "12.5%", "15%", "20%"},
            {"20 days", "27 days", "30 days", "36 days"},
            {"10 minutes", "12 minutes", "15 minutes", "25 minutes"},
            {"1/6", "1/9", "1/8", "1/12"},
            {"12 years", "14 years", "15 years", "13.5 years"},
            {"Rs. 1000", "Rs. 1125", "Rs. 1200", "Rs. 1250"},
            {"360", "720", "1440", "180"},
            {"12 km", "6 km", "9 km", "4.5 km"},
            {"8 days", "9 days", "10 days", "12 days"},
            {"1.5 years", "2 years", "2.5 years", "3 years"},
            {"48 km/h", "50 km/h", "52 km/h", "55 km/h"},
            {"Rs. 600", "Rs. 625", "Rs. 700", "Rs. 750"},
            {"a", "2a", "b", "10"},
            {"12%", "15%", "14.29%", "13%"},
            {"12 days", "16 days", "18 days", "20 days"},
            {"4% decrease", "4% increase", "No change", "5% decrease"},
            {"15 years", "18 years", "20 years", "24 years"},
            {"16 days", "20 days", "24 days", "32 days"},
            {"1 sq km", "2 sq km", "2.16 sq km", "3 sq km"},
            {"16%", "20%", "25%", "30%"},
            {"5%", "6%", "7%", "8%"},
            {"251", "301", "361", "401"}
    };

    public static String correctAnswers[] = {
            "150 meters",
            "10 km",
            "9",
            "12.5%",
            "27 days",
            "12 minutes",
            "1/9",
            "13.5 years",
            "Rs. 2000",
            "360",
            "6 km",
            "10 days",
            "2 years",
            "48 km/h",
            "Rs. 600",
            "a",
            "14.29%",
            "16 days",
            "4% decrease",
            "15 years",
            "24 days",
            "2.16 sq km",
            "20%",
            "7%",
            "361"
    };
}
