package com.example.sampleminorproject;

public class QuestionAnswerIQ {
    public static String question[] = {
            "What is the next number in the series : 2, 4, 8, 16, ?",
            "Which of the following is the odd one out?",
            "If you rearrange the letters 'CIFAIPC', you would have the name of a :",
            "What is the result of 15 + 25 ÷ 5?",
            "Which word does NOT belong with the others?",
            "What is the missing number in the series: 3, 6, 11, 18, ?",
            "Which number is least like the others?",
            "If you rearrange the letters 'LISTEN', you would have the name of a:",
            "What is the result of 12 ÷ 4 × 3?",
            "Which word does NOT belong with the others?",
            "What is the next number in the series: 1, 1, 2, 3, 5, ?",
            "Which shape does NOT belong with the others?",
            "If you rearrange the letters 'SHOEL', you would have the name of a:",
            "What is the next number in the series: 5, 10, 20, 40, ?",
            "Which number is the odd one out?",
            "If you rearrange the letters 'CINEMA', you would have the name of a:",
            "What is the result of 10 - 3 × 2 + 6 ÷ 2?",
            "Which word does NOT belong with the others?",
            "What is the next number in the series: 7, 14, 28, 56, ?",
            "Which shape does NOT belong with the others?",
            "If you rearrange the letters 'RACECAR', you would have the name of a:",
            "What is the result of 8 × (2 + 2)?",
            "Which number is the odd one out?",
            "If you rearrange the letters 'ELPPA', you would have the name of a:",
            "What is the next number in the series: 2, 5, 10, 17, ?"
    };

    public static String[][] choices = {
            {"20", "24", "32", "64"},
            {"Apple", "Banana", "Carrot", "Grapes"},
            {"Country", "City", "Animal", "Ocean"},
            {"8", "10", "20", "30"},
            {"Dog", "Cat", "Lion", "Orange"},
            {"25", "24", "23", "22"},
            {"2", "3", "5", "8"},
            {"Silent", "Listen", "Inlets", "Tinsel"},
            {"9", "12", "6", "3"},
            {"Apple", "Orange", "Grape", "Car"},
            {"8", "5", "3", "13"},
            {"Circle", "Square", "Rectangle", "Triangle"},
            {"Shoe", "Hole", "Shell", "Helos"},
            {"80", "100", "60", "50"},
            {"12", "14", "15", "16"},
            {"Iceman", "Anemic", "Maine", "Menica"},
            {"9", "10", "8", "12"},
            {"Carrot", "Tiger", "Bear", "Lion"},
            {"112", "120", "100", "110"},
            {"Triangle", "Square", "Hexagon", "Pentagon"},
            {"Racecar", "Race", "Care", "Arc"},
            {"32", "24", "20", "16"},
            {"9", "15", "25", "30"},
            {"Apple", "Plea", "Leap", "ELPPA"},
            {"26", "30", "24", "25"}
    };

    public static String correctAnswers[] = {
            "32",
            "Carrot",
            "Ocean",
            "20",
            "Orange",
            "25",
            "8",
            "Silent",
            "9",
            "Car",
            "8",
            "Circle",
            "Shoe",
            "80",
            "15",
            "Iceman",
            "9",
            "Carrot",
            "112",
            "Triangle",
            "Racecar",
            "32",
            "30",
            "Apple",
            "26"
    };
}
